services:
  postgres:
    image: postgres:16
    container_name: demo-postgres
    environment:
      POSTGRES_USER: vault_admin
      POSTGRES_PASSWORD: vault_admin_pass
      POSTGRES_DB: mydb
    volumes:
      # mount sql files for initialization
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  vault:
    image: hashicorp/vault:1.19
    container_name: demo-vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
    ports:
      - "8200:8200"
    command: server -dev -dev-root-token-id=root
